version: "3.9"
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/client
      - /node_modules
    ports:
      - "8080:8080"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./server:/server
      - /server/node_modules
    ports:
      - "3000:3000"
  db:
    image: mysql
    cap_add:
      - SYS_NICE
    ports:
      - '3999:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSSQL_DATABASE: my_db
      MYSQL_PASSWORD: 123456
    volumes:
      - mysql_db:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    command: ['mysqld', '--default-authentication-plugin=mysql_native_password']
volumes:
  mysql_db: {}
